apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: composite-resource
spec:
  crossplane:
    version: ">=v1.0.0-0"
  dependsOn:
    - provider: crossplane/provider-aws
      version: "v0.20.0"